VUETIFY_MAP = {
    "ui": "div",
    "row": "v-row",
    "col": "v-col",
    "spacer": "v-spacer",
    "divider": "v-divider",
    "show": "sw-show",
    "hide": "sw-hide",
    "text": "sw-text",
}

WIDGET_MAP = {
    "input": "sw-text-field",
    "textarea": "sw-text-area",
}

WIDGET_KNOWN = {
    # HTML
    "div",
    # Vuetify
    "v-alert",
    "v-app-bar-nav-icon",
    "v-app-bar-title",
    "v-app-bar",
    "v-app",
    "v-autocomplete",
    "v-avatar",
    "v-badge",
    "v-banner",
    "v-bottom-navigation",
    "v-bottom-sheet",
    "v-breadcrumbs-divider",
    "v-breadcrumbs-item",
    "v-breadcrumbs",
    "v-btn-toggle",
    "v-btn",
    "v-calendar-category",
    "v-calendar-daily",
    "v-calendar-monthly",
    "v-calendar-weekly",
    "v-calendar",
    "v-card",
    "v-carousel-item",
    "v-carousel",
    "v-checkbox",
    "v-chip-group",
    "v-chip",
    "v-col",
    "v-color-picker-canvas",
    "v-color-picker-edit",
    "v-color-picker-preview",
    "v-color-picker-swatches",
    "v-color-picker",
    "v-combobox",
    "v-container",
    "v-content",
    "v-counter",
    "v-data-footer",
    "v-data-iterator",
    "v-data-table-header-desktop",
    "v-data-table-header-mobile",
    "v-data-table-header",
    "v-data-table",
    "v-data",
    "v-date-picker-date-table",
    "v-date-picker-header",
    "v-date-picker-month-table",
    "v-date-picker-title",
    "v-date-picker-years",
    "v-date-picker",
    "v-dialog",
    "v-divider",
    "v-edit-dialog",
    "v-expansion-panel-content",
    "v-expansion-panel-header",
    "v-expansion-panel",
    "v-expansion-panels",
    "v-file-input",
    "v-flex",
    "v-footer",
    "v-form",
    "v-hover",
    "v-icon",
    "v-img",
    "v-input",
    "v-item-group",
    "v-item",
    "v-label",
    "v-layout",
    "v-lazy",
    "v-list-group",
    "v-list-item-action",
    "v-list-item-avatar",
    "v-list-item-group",
    "v-list-item-icon",
    "v-list-item",
    "v-list",
    "v-main",
    "v-menu",
    "v-messages",
    "v-navigation-drawer",
    "v-otp-input",
    "v-overflow-btn",
    "v-overlay",
    "v-pagination",
    "v-parallax",
    "v-picker",
    "v-progress-circular",
    "v-progress-linear",
    "v-radio-group",
    "v-radio",
    "v-range-slider",
    "v-rating",
    "v-responsive",
    "v-row",
    "v-select-list",
    "v-select",
    "v-sheet",
    "v-simple-checkbox",
    "v-simple-table",
    "v-skeleton-loader",
    "v-slide-group",
    "v-slide-item",
    "v-slider",
    "v-snackbar",
    "v-spacer",
    "v-sparkline",
    "v-speed-dial",
    "v-stepper-content",
    "v-stepper-step",
    "v-stepper",
    "v-subheader",
    "v-switch",
    "v-system-bar",
    "v-tab-item",
    "v-tab",
    "v-tabs-bar",
    "v-tabs-items",
    "v-tabs-slider",
    "v-tabs",
    "v-text-field",
    "v-textarea",
    "v-theme-provider",
    "v-time-picker-clock",
    "v-time-picker-title",
    "v-time-picker",
    "v-timeline-item",
    "v-timeline",
    "v-toolbar",
    "v-tooltip",
    "v-treeview-node",
    "v-treeview",
    "v-virtual-scroll",
    "v-virtual-table",
    "v-window-item",
    "v-window",
    # SW
    "sw-show",
    "sw-hide",
    "sw-text",
    "sw-text-field",
    "sw-text-area",
    "sw-slider",
    "sw-group",
}
